[project]
name = "whitepages-cli"
version = "0.1.0"
description = "Search for a person on the WhitePages"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.13",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]
